run:
  deadline: 10m

issues:
  max-same-issues: 0
  max-per-linter: 0
  exclude-use-default: false

  # we remove a few annoying gosec rules:
  # G104 is used for errcheck. It gets triggered on places that don't
  #      don't need it like (*bytes.Buffer).Write(), and we already have
  #      errcheck.
  exclude-rules:
    - linters:
        - gosec
      text: "G104"

    - linters:
        - govet
      text: 'shadow: declaration of "err"'

    # we remove a few annoying things from our tests, because they
    # don't provide much beside complexity
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - maligned

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

    - bodyclose
    - golint
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - asciicheck
    - goimports
    - maligned
    - misspell
    - unparam
    - dogsled
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - whitespace
    - goprintffuncname
    - exhaustive
    - nolintlint
    - noctx
    - exportloopref
    - gofumpt # replaces gofmt

linters-settings:
  govet:
    check-shadowing: true

  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - experimental
      - opinionated

    disabled-checks:
      - sloppyReassign
      - emptyFallthrough
      - octalLiteral
      - hugeParam # disabled because we pass option objects by copy
