version: "3"
services:
  api:
    container_name: logan_api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 80:5000
    volumes:
      - ./:/app
    depends_on:
      - database
    environment:
      - PORT=5000
      - LOGAN_POSTGRES_DSN=user=pguser password=pguser dbname=api-logan host=logan_api_postgres sslmode=disable
    working_dir: /app
    command:
      [
        "./scripts/wait-for-it.sh",
        "database:5432",
        "--",
        "task",
        "api-local-dev",
        "-w",
      ]

  database:
    container_name: logan_api_postgres
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=api-logan
      - POSTGRES_INITDB_ARGS="-E 'UTF-8'"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "$${POSTGRES_DB}",
          "-U",
          "$${POSTGRES_USER}",
          "-p",
          "$${POSTGRES_PASSWORD}",
        ]
      interval: 1s
      timeout: 10s
      retries: 10
