name: api
on: [push]
jobs:
  go-vulnerabilities-scan:
    name: "Golang Vulnerabilities Scan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Run Nancy
        working-directory: ./go
        run: go list -m all | docker run -i sonatypecommunity/nancy:v0

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
          working-directory: ./go

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Build
        working-directory: ./go
        run: go build -race ./...
